### ISSUE TITLE
Prior to execution, the Python "run script" should delete Litani cache pointers present inside individual proof directories

### ISSUE THREAD

**Issue by angelonakos** [model-checking/cbmc-starter-kit#116]
** Issue **

If the directory for a particular CBMC proof has the .litani_cache_dir file present, then the Python "run script" will fail.

** Acceptance Criteria **

- If one or multiple CBMC proof directories have "Litani cache pointers" present, then no failure will be encountered when running the Python "run script" from the directory containing all proofs.

**Comment by tautschnig** [comment]
Resolving as #117 has been merged.
