### ISSUE TITLE
Remove cbmc-batch and report1 from Makefile.common

### ISSUE THREAD

**Issue by markrtuttle** [model-checking/cbmc-starter-kit#127]
Let's modify Makefile.common to remove the set-up for cbmc-batch (eg, the cbmc-batch.yaml reference) and to remove the set-up for dispatching on cbmc-viewer1 versus cbmc-viewer2 (eg, the _report, _report1,  _report2 reference).

**Comment by feliperodri** [comment]
https://github.com/model-checking/cbmc-starter-kit/pull/136
