### ISSUE TITLE
Add versioning to ProofCI GitHub Actions workflow file

### ISSUE THREAD

**Issue by angelonakos** [model-checking/cbmc-starter-kit#173]
@kstribrnAmzn asked during a demo of the ProofCI GitHub Actions whether the workflow file is versioned.  It currently isn't.

We should **add** a comment within [proof_ci.yaml](https://github.com/model-checking/cbmc-starter-kit/blob/master/src/cbmc_starter_kit/template-for-ci-workflow/proof_ci.yaml) that indicates the version of the CBMC starter-kit that generated/contributed this workflow file à la Makefile.common

**Comment by kstribrnAmzn** [comment]
Thanks for tagging me here! I'll keep my eyes on this issue as it progresses.

**Comment by angelonakos** [comment]
Resolved.
