### ISSUE TITLE
Go on PR campaign to add FreeRTOS central repository workflow to each repo

### ISSUE THREAD

**Issue by karkhaz** [model-checking/cbmc-starter-kit#182]
- [x] https://github.com/FreeRTOS/CI-CD-Github-Actions/pull/58

then

- [x] https://github.com/aws/Device-Defender-for-AWS-IoT-embedded-sdk/pull/70 ([successful run](https://github.com/aws/Device-Defender-for-AWS-IoT-embedded-sdk/actions/runs/4297908877/jobs/7491448292))
- [x] https://github.com/aws/Device-Shadow-for-AWS-IoT-embedded-sdk/pull/113 ([successful run](https://github.com/aws/Device-Shadow-for-AWS-IoT-embedded-sdk/actions/runs/4297909488/jobs/7491449069))
- [x] https://github.com/FreeRTOS/coreMQTT/pull/241 ([successful run](https://github.com/FreeRTOS/coreMQTT/actions/runs/4298053863/jobs/7491739162))
- [x] https://github.com/aws/SigV4-for-AWS-IoT-embedded-sdk/pull/78 ([successful run](https://github.com/aws/SigV4-for-AWS-IoT-embedded-sdk/actions/runs/4298084313/jobs/7491805078))
- [x] https://github.com/FreeRTOS/coreSNTP/pull/71 ([successful run](https://github.com/FreeRTOS/coreSNTP/actions/runs/4297989163/jobs/7491608666))
- [x] https://github.com/FreeRTOS/coreMQTT-Agent/pull/83 ([successful run](https://github.com/FreeRTOS/coreMQTT-Agent/actions/runs/4297906953/jobs/7491444124))
- [x] https://github.com/FreeRTOS/corePKCS11/pull/166 ([successful run](https://github.com/FreeRTOS/corePKCS11/actions/runs/4307278319/jobs/7512143534))
- [x] https://github.com/FreeRTOS/coreJSON/pull/137 ([successful run](https://github.com/FreeRTOS/coreJSON/actions/runs/4307675392/jobs/7513030425))
- [x] https://github.com/FreeRTOS/FreeRTOS/pull/924 ([successful run](https://github.com/FreeRTOS/FreeRTOS/actions/runs/4324564920/jobs/7549563689))
- [x] https://github.com/aws/ota-for-aws-iot-embedded-sdk/pull/474 ([successful run](https://github.com/aws/ota-for-aws-iot-embedded-sdk/actions/runs/4356168503/jobs/7613801473))
- [x] https://github.com/aws/Jobs-for-AWS-IoT-embedded-sdk/pull/76 ([successful run](https://github.com/aws/Jobs-for-AWS-IoT-embedded-sdk/actions/runs/4297904566/jobs/7491440109))
- [x] https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/733 ([successful run](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/actions/runs/4365280383/jobs/7633690662))
- [x] https://github.com/FreeRTOS/FreeRTOS-Cellular-Interface/pull/132
- [x] https://github.com/FreeRTOS/coreHTTP/pull/153

**Comment by tautschnig** [comment]
Closing as all repositories are covered.
