### ISSUE TITLE
Standard definition for bounded_malloc

### ISSUE THREAD

**Issue by feliperodri** [model-checking/cbmc-starter-kit#31]
In CBMC, if we call malloc with 0, we get an invalid pointer, which triggers failed primitive checks everywhere. For instance, in [FreeRTOS](https://github.com/FreeRTOS/FreeRTOS), the `safeMalloc` function is required to return NULL for zero-size `malloc`s. (see [safeMalloc](https://github.com/FreeRTOS/FreeRTOS/blob/d95624c5d6ba95ec0474867d7165de2c28ed41b7/FreeRTOS-Plus/Test/CBMC/proofs/parsing/ProcessReceivedTCPPacket/ProcessReceivedTCPPacket_harness.c#L19)). According with the [standard](https://en.cppreference.com/w/c/memory/malloc): 
> If size is zero, the behavior of malloc is implementation-defined. For example, a null pointer may be returned. Alternatively, a non-null pointer may be returned; but such a pointer should not be dereferenced, and should be passed to free to avoid memory leaks.

So we could update the implementation to something like, i.e.,
```c
void *bounded_malloc(size_t size) {
    __CPROVER_assume(size <= MAX_MALLOC);
    if (size == 0) {
        if (nondet_bool()) {
            return NULL
        }
        return malloc(1);
    }
    return malloc(size);
}
```

We also should make sure we adopt this across of our projects.
@danielsn @SaswatPadhi @danielsn @tegansb

**Comment by markrtuttle** [comment]
One of the known problems with pointer primitive check.  I think we should
leave documentation in Makefile-project-defines to remove the flag if it
causes trouble for a project.  But I think our group has decided that it is
best practice.

**Comment by feliperodri** [comment]
@markrtuttle AFAIK, we don't use these `bounded_malloc` anymore. So, can we close this issue?
