### ISSUE TITLE
An error occurred when applying CHECK_FUNCTION_CONTRACTS  to a function with loops.

### ISSUE THREAD

**Issue by xiaolangde** [model-checking/cbmc-starter-kit#87]
I test according to [Function-contract-tutorial](https://github.com/awslabs/aws-templates-for-cbmc-proofs/wiki/Function-contract-tutorial). And use the [modified proof harness](https://github.com/awslabs/aws-templates-for-cbmc-proofs/wiki/function-contract-tutorial/tests/cbmc/proofs/s2n_stuffer_skip_to_char/s2n_stuffer_skip_to_char_harness.c) , [modified Makefile](https://github.com/awslabs/aws-templates-for-cbmc-proofs/wiki/function-contract-tutorial/tests/cbmc/proofs/s2n_stuffer_skip_to_char/Makefile), and [modified source file](https://github.com/awslabs/aws-templates-for-cbmc-proofs/wiki/function-contract-tutorial/stuffer/s2n_stuffer_text.c)..
The `s2n_stuffer_skip_to_char: checking function contracts` step fails, and report:
```
Invariant check failed
File: ../src/goto-instrument/contracts/contracts.cpp:1204 function: check_frame_conditions_function
Condition: is_loop_free(function_body, ns, log)
Reason: Loops remain in function 's2n_stuffer_skip_to_char', assigns clause checking instrumentation cannot be applied.
```
It seems that `--enforce-contract` option of goto-instrument cannot be used for functions with loops before `--apply-loop-contracts` be used. There was an error before we went to the step of applying `UNWINDSET += __CPROVER_contracts_original_s2n_stuffer_skip_to_char.1:$(call addone,$(MAX_BLOB_SIZE))
` ,  so what is the application scenario of `__CPROVER_contracts_original_xxx.m:n`.

**Comment by feliperodri** [comment]
Hi @xiaolangde! Thanks for reporting this error. The modified Makefile is out of date, since you know longer need to use the mangled name of functions with contracts to unroll loops. If you use the following Makefile in your example, everything should work as expected.
```Makefile
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may not use
# this file except in compliance with the License. A copy of the License is
# located at
#
#     http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing permissions and
# limitations under the License.

# Enough to get full coverage with 40 seconds of runtime.
MAX_BLOB_SIZE = 10
DEFINES += -DMAX_BLOB_SIZE=$(MAX_BLOB_SIZE)

PROOF_UID = s2n_stuffer_skip_to_char
HARNESS_ENTRY = $(PROOF_UID)_harness
HARNESS_FILE = $(HARNESS_ENTRY).c

PROOF_SOURCES += $(PROOFDIR)/$(HARNESS_FILE)
PROOF_SOURCES += $(PROOF_SOURCE)/cbmc_utils.c
PROOF_SOURCES += $(PROOF_SOURCE)/make_common_datastructures.c

PROJECT_SOURCES += $(SRCDIR)/stuffer/s2n_stuffer.c
PROJECT_SOURCES += $(SRCDIR)/stuffer/s2n_stuffer_text.c
PROJECT_SOURCES += $(SRCDIR)/stuffer/s2n_stuffer_network_order.c
PROJECT_SOURCES += $(SRCDIR)/utils/s2n_blob.c
PROJECT_SOURCES += $(SRCDIR)/utils/s2n_ensure.c
PROJECT_SOURCES += $(SRCDIR)/utils/s2n_result.c

UNWINDSET += s2n_stuffer_skip_to_char.1:$(call addone,$(MAX_BLOB_SIZE))

CHECK_FUNCTION_CONTRACTS += s2n_stuffer_skip_to_char

include ../Makefile.common
```

I ran this example using CBMC v5.56.0, but few free to use the latest available version. Hope that helps.
