### ISSUE TITLE
Spurious unwindset-does-not-match-any-loop warnings

### ISSUE THREAD

**Issue by tautschnig** [model-checking/cbmc-starter-kit#88]
We had two changes the combination of which may result in spurious warnings:
- As of dbf54250243dfa4c we perform (some) loop unwinding using goto-instrument.
- With CBMC versions >= 5.46.0, there are warnings issued for loop identifiers that occur in --unwindset, but don't actually exist in the program. With goto-instrument's loop unwinding, loops are removed, and cbmc will therefore complain about non-existent loops.

Users will now see a mix of genuine and spurious warnings about non-existent loops. To avoid warning fatigue, we should figure out a way to avoid spurious (while still keeping the genuine ones!) warnings.

**Comment by markrtuttle** [comment]
Resolved by https://github.com/model-checking/cbmc-starter-kit/pull/110
